apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: bulletin
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bulletins # i will change db with db service's name when i set it


