apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: bulletin
stringData:
  POSTGRES_USER: FrankyGaliano
  POSTGRES_PASSWORD: Alavidaalamuerte9mm
  POSTGRES_DB: bulletins
  SPRING_DATASOURCE_USERNAME: FrankyGaliano
  SPRING_DATASOURCE_PASSWORD: Alavidaalamuerte9mm
