apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: bulletin
stringData:
  POSTGRES_USER: FrankyGaliano
  POSTGRES_PASSWORD: Alavidaalamuerte9mm
  POSTGRES_DB: bulletins
  SPRING_DATASOURCE_USERNAME: FrankyGaliano
  SPRING_DATASOURCE_PASSWORD: Alavidaalamuerte9mm
  STORAGE_S3_BUCKET: bulletin-images
  STORAGE_S3_REGION: us-east-1
  STORAGE_S3_ENDPOINT: http://minio-service:9000
  STORAGE_S3_CDNURL: http://bulletin.local/minio/bulletin-images
