apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: bulletin

spec:
  schedule: "0 2 * * *"

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          containers:
            - name: postgres-backup
              image: nighthawk777/postgres-backup:1.0
              imagePullPolicy: Always

              envFrom:
                - secretRef:
                    name: postgres-secret
                - secretRef:
                    name: minio-secret

              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 1000

              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
