apiVersion: v1
data:
  MINIO_BROWSER_REDIRECT_URL: aHR0cDovL2J1bGxldGluLmxvY2FsL21pbmlv
  MINIO_ENDPOINT: aHR0cDovL21pbmlvLXNlcnZpY2U6OTAwMA==
  MINIO_ROOT_PASSWORD: QWxhdmlkYWFsYW11ZXJ0ZTltbQ==
  MINIO_ROOT_USER: RnJhbmt5R2FsaWFubw==
  MINIO_SERVER_URL: aHR0cDovL2J1bGxldGluLmxvY2FsLw==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"minio-secret","namespace":"bulletin"},"stringData":{"MINIO_BROWSER_REDIRECT_URL":"http://bulletin.local/minio","MINIO_ENDPOINT":"http://minio-service:9000","MINIO_ROOT_PASSWORD":"Alavidaalamuerte9mm","MINIO_ROOT_USER":"FrankyGaliano","MINIO_SERVER_URL":"http://bulletin.local/"}}
  creationTimestamp: "2026-07-07T03:08:18Z"
  name: minio-secret
  namespace: bulletin
  resourceVersion: "256393"
  uid: 07426c26-dfb7-49a0-b012-6a0b7cecfcd7
type: Opaque
