apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: bulletin
stringData:
  MINIO_ROOT_USER: FrankyGaliano
  MINIO_ROOT_PASSWORD: Alavidaalamuerte9mm
  MINIO_BROWSER_REDIRECT_URL: http://bulletin.local/minio
  MINIO_SERVER_URL: http://bulletin.local/
  MINIO_ENDPOINT: http://minio-service:9000
