apiVersion: v1
kind: LimitRange

metadata:
  name: bulletin-limit-range
  namespace: bulletin

spec:
  limits:
    - type: Container

      min:
        cpu: "100m"
        memory: "128Mi"

      max:
        cpu: "500m"
        memory: "512Mi"

