apiVersion: v1
kind: ResourceQuota

metadata:
  name: bulletin-resource-quota
  namespace: bulletin

spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "3"

    requests.memory: 1Gi
    limits.memory: 3Gi
