apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bulletin
stringData:
  POSTGRES_HOST: postgres-service
  POSTGRES_USER: FrankyGaliano
  POSTGRES_PASSWORD: Alavidaalamuerte9mm
  POSTGRES_DB: bulletins
